name: wangyiyun
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # 适配
  flutter_screenutil: ^1.0.2
  # 轮播
  flutter_swiper: ^1.1.6
  # 本地存储
  shared_preferences: ^0.5.7+2
  # provide
  provider: ^4.1.2
  # bot_toast
  bot_toast: ^3.0.0
  # dio
  dio: ^3.0.9
  # dio_http2_adapter
  dio_http2_adapter: ^1.0.0 
  # fluro
  fluro: ^1.6.3
  # 地图
  amap_location: ^0.2.0
  # 扫一扫
  qr_code_scanner: ^0.0.13
  # 打开其他app
  url_launcher: ^5.4.10
  # 打开微信
  fluwx: ^2.1.0
  # 支付宝支付
  # flutter_alipay: ^1.0.0
  # 上啦加载
  pull_to_refresh: ^1.5.8
  # 检查网络状态
  connectivity: ^0.4.8+6
  # 获取缓存
  path_provider: ^1.6.9
  # 获取版本号
  package_info: ^0.4.0+18
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/index.jpeg
   - images/loading.gif
   - images/scan.png
   - images/right.png
   - images/friends.png
   - images/shirt.png
   - images/email.png
   - images/home.png
   - images/sign.png
   - images/bulb.png # 创作者
   - images/tickets.png # 演出
   - images/shop.png # 商城
   - images/ringtone.png # 彩铃
   - images/wallet.png # 在线听歌免流量
   - images/setting.png # 设置
   - images/night.png # 夜间模式
   - images/timing.png # 定时关闭
   - images/stop.png # 音乐黑名单
   - images/clock.png # 音乐闹钟
   - images/security.png # 青少年模式
   - images/microphone.png # 麦克风
   - images/seach.png #搜索
   - images/triangle.png #右三角
   - images/equalizer.png #均衡器
   - images/placeholder.png #均衡器



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
